// Package er1 handles ER1 server configuration, multipart uploads,
// and offline retry queuing.
package er1

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Config holds ER1 server connection settings, loaded from environment variables.
type Config struct {
	APIURL        string // ER1 upload endpoint (default: https://127.0.0.1:8081/upload_2)
	APIKey        string // X-API-KEY header value
	ContextID     string // context_id form field
	ContentType   string // content_type form field
	UploadTimeout int    // HTTP timeout in seconds
	VerifySSL     bool   // whether to verify TLS certificates
	RetryInterval int    // seconds between retry cycles
	MaxRetries    int    // max retry attempts before dropping
}

// LoadConfig reads ER1 settings from environment variables.
func LoadConfig() *Config {
	return &Config{
		APIURL:        envOr("ER1_API_URL", "https://127.0.0.1:8081/upload_2"),
		APIKey:        os.Getenv("ER1_API_KEY"),
		ContextID:     envOr("ER1_CONTEXT_ID", "107677460544181387647___mft"),
		ContentType:   envOr("ER1_CONTENT_TYPE", "YouTube-Video-Impression"),
		UploadTimeout: envInt("ER1_UPLOAD_TIMEOUT", 600),
		VerifySSL:     envBool("ER1_VERIFY_SSL", true),
		RetryInterval: envInt("ER1_RETRY_INTERVAL", 300),
		MaxRetries:    envInt("ER1_MAX_RETRIES", 10),
	}
}

// AuthHeaders returns HTTP headers with X-API-KEY if configured.
func (c *Config) AuthHeaders() map[string]string {
	h := map[string]string{}
	if c.APIKey != "" {
		h["X-API-KEY"] = c.APIKey
	}
	return h
}

// Summary returns a human-readable one-liner for logging.
func (c *Config) Summary() string {
	masked := "(none)"
	if c.APIKey != "" {
		masked = fmt.Sprintf("****(%d chars)", len(c.APIKey))
	}
	return fmt.Sprintf("ER1 -> %s key=%s ctx=%s timeout=%ds ssl=%v",
		c.APIURL, masked, c.ContextID, c.UploadTimeout, c.VerifySSL)
}

// LoadDotenv loads a .env file into os.Environ (does not override existing vars).
func LoadDotenv(path string) error {
	info, statErr := os.Stat(path)
	if statErr != nil {
		return statErr
	}
	if info.Mode().Perm()&0077 != 0 {
		fmt.Fprintf(os.Stderr, "Warning: %s has permissive permissions (%04o). Consider: chmod 600 %s\n",
			path, info.Mode().Perm(), path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(v)
		// Strip surrounding quotes
		if len(v) >= 2 && ((v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'')) {
			v = v[1 : len(v)-1]
		}
		if os.Getenv(k) == "" {
			os.Setenv(k, v)
		}
	}
	return nil
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func envInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return fallback
}

func envBool(key string, fallback bool) bool {
	v := strings.ToLower(os.Getenv(key))
	switch v {
	case "true", "1", "yes":
		return true
	case "false", "0", "no":
		return false
	}
	return fallback
}

// WriteConfig writes ER1 and Plaud configuration to ~/.m3c-tools.env.
// It creates or overwrites the file with 0600 permissions.
func WriteConfig(apiURL, apiKey, contextID string, verifySSL bool, defaultTags string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("get home dir: %w", err)
	}
	path := filepath.Join(home, ".m3c-tools.env")

	now := time.Now().Format("2006-01-02")
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Generated by m3c-tools setup on %s\n", now))
	b.WriteString(fmt.Sprintf("ER1_API_URL=%s\n", apiURL))
	b.WriteString(fmt.Sprintf("ER1_API_KEY=%s\n", apiKey))
	b.WriteString(fmt.Sprintf("ER1_CONTEXT_ID=%s\n", contextID))
	b.WriteString(fmt.Sprintf("ER1_VERIFY_SSL=%v\n", verifySSL))
	b.WriteString("\n# Plaud sync defaults\n")
	b.WriteString(fmt.Sprintf("PLAUD_DEFAULT_TAGS=%s\n", defaultTags))

	if err := os.WriteFile(path, []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// ConfigPath returns the path to ~/.m3c-tools.env.
func ConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".m3c-tools.env")
}
