// Package a is the Artifact-layer processor. Week 1 strategies:
// report, summary. When the last step of a process is an A-step,
// the handler also emits ProcessCompleted via the orchestrator.
package a

import (
	"context"
	"time"

	"github.com/google/uuid"
	tkafka "github.com/kamir/m3c-tools/internal/thinking/kafka"
	"github.com/kamir/m3c-tools/internal/thinking/processors"
	"github.com/kamir/m3c-tools/internal/thinking/prompts"
	"github.com/kamir/m3c-tools/internal/thinking/schema"
)

type Processor struct {
	deps processors.Deps
	stop func()
}

func New(deps processors.Deps) *Processor {
	return &Processor{deps: deps}
}

var strategies = map[string]processors.Handler{
	"report":  handleReport,
	"summary": handleSummary,
}

func (p *Processor) Start(ctx context.Context) error {
	stop, err := p.deps.Bus.Subscribe(p.deps.Orc.CmdTopic(), func(hctx context.Context, m tkafka.Message) error {
		cmd, err := processors.DecodeCommand(m)
		if err != nil {
			return err
		}
		if cmd.Step.Layer != schema.LayerA {
			return nil
		}
		h, ok := strategies[cmd.Step.Strategy]
		if !ok {
			_ = p.deps.Orc.EmitProcessFailed(ctx, cmd.ProcessID, processors.UnknownStrategyError(schema.LayerA, cmd.Step.Strategy).Error())
			return nil
		}

		// Run the handler directly (not via processors.RunStep) so we
		// can capture the artifact ID for Complete(). We still emit
		// StepStarted/StepCompleted to keep the lifecycle observable.
		_ = p.deps.Orc.EmitStepStarted(ctx, cmd.ProcessID, cmd.StepIndex, cmd.Step.Layer)
		select {
		case <-time.After(100 * time.Millisecond):
		case <-ctx.Done():
			return nil
		}
		detail, err := h(ctx, p.deps, cmd)
		if err != nil {
			_ = p.deps.Orc.EmitProcessFailed(ctx, cmd.ProcessID, err.Error())
			return nil
		}
		_ = p.deps.Orc.EmitStepCompleted(ctx, cmd.ProcessID, cmd.StepIndex, cmd.Step.Layer, detail)

		// If this is the last step, close out the process, rolling
		// the artifact ID into Complete() so the store + UI see it.
		if cmd.StepIndex == len(cmd.Spec.Steps)-1 {
			var artifactIDs []string
			if id, ok := detail["artifact_id"].(string); ok && id != "" {
				artifactIDs = []string{id}
			}
			_ = p.deps.Orc.Complete(ctx, cmd.ProcessID, artifactIDs)
		}
		return nil
	})
	if err != nil {
		return err
	}
	p.stop = stop
	p.deps.Log.Printf("a-proc: subscribed (strategies: report, summary)")
	return nil
}

func (p *Processor) Stop() {
	if p.stop != nil {
		p.stop()
	}
}

func handleReport(ctx context.Context, deps processors.Deps, cmd schema.ProcessCommand) (map[string]interface{}, error) {
	return emitArtifact(ctx, deps, cmd, schema.FormatReport, "report")
}
func handleSummary(ctx context.Context, deps processors.Deps, cmd schema.ProcessCommand) (map[string]interface{}, error) {
	return emitArtifact(ctx, deps, cmd, schema.FormatSummary, "summary")
}

func emitArtifact(ctx context.Context, deps processors.Deps, cmd schema.ProcessCommand, format schema.ArtifactFormat, strName string) (map[string]interface{}, error) {
	promptID := prompts.DefaultStrategyPromptID("a", strName)
	p, err := deps.Prompts.Get(ctx, promptID)
	if err != nil {
		return nil, err
	}
	art := schema.Artifact{
		SchemaVer:  schema.CurrentSchemaVer,
		ArtifactID: uuid.NewString(),
		InsightIDs: []string{"[stub]"},
		Format:     format,
		Audience:   schema.AudienceHuman,
		Content: map[string]interface{}{
			"title":  "[stub] " + strName,
			"body":   "placeholder artifact generated by Week 1 scaffold",
			"prompt": p.Body,
		},
		Version: 1,
		Provenance: schema.ArtifactProvenance{
			TIDs: []string{"[stub]"},
			RIDs: []string{"[stub]"},
			IIDs: []string{"[stub]"},
		},
		Timestamp: time.Now().UTC(),
		ProcessID: cmd.ProcessID,
	}
	topic := tkafka.TopicName(deps.Hash, tkafka.TopicArtifactsCreated)
	if err := deps.Bus.Produce(ctx, topic, art.ArtifactID, art); err != nil {
		return nil, err
	}
	return map[string]interface{}{
		"artifact_id": art.ArtifactID,
		"format":      string(format),
	}, nil
}
