package skillgate

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// TestCanonicalize_DeterministicAcrossCalls — same token → same bytes.
func TestCanonicalize_DeterministicAcrossCalls(t *testing.T) {
	tok := &Token{
		Schema:         "m3c-skill-capability/v1",
		TokenID:        "ct:01HZTESTTESTTESTTESTTESTTE",
		IssuedAt:       "2026-05-10T00:00:00Z",
		ExpiresAt:      "2026-05-10T00:05:00Z",
		BundleDigest:   "sha256:abc",
		SkillName:      "demo",
		SkillVersion:   "0.1.0",
		CallerIdentity: "id:tester",
		CallerSession:  "sess:01HZSESSIONSESSIONSESSIO",
		Envelope: TokenEnvelope{
			Capabilities:        []string{"fs:read", "egress"},
			EgressAllowlist:     []string{"api.example.com:443"},
			SubprocessAllowlist: []string{"git", "bash"},
		},
		RegistryKeyID: "registry-2026",
	}
	b1, err := CanonicalizeToken(tok)
	if err != nil {
		t.Fatalf("call 1: %v", err)
	}
	b2, err := CanonicalizeToken(tok)
	if err != nil {
		t.Fatalf("call 2: %v", err)
	}
	if string(b1) != string(b2) {
		t.Errorf("non-deterministic canonical bytes:\n  b1=%q\n  b2=%q", b1, b2)
	}
}

// TestCanonicalize_SortsLists — capability/allowlist/denylist must be sorted.
func TestCanonicalize_SortsLists(t *testing.T) {
	unsorted := &Token{
		Schema:         "m3c-skill-capability/v1",
		TokenID:        "ct:01HZTESTTESTTESTTESTTESTTE",
		IssuedAt:       "2026-05-10T00:00:00Z",
		ExpiresAt:      "2026-05-10T00:05:00Z",
		BundleDigest:   "sha256:abc",
		SkillName:      "demo",
		SkillVersion:   "0.1.0",
		CallerIdentity: "id:tester",
		CallerSession:  "sess:01HZSESSIONSESSIONSESSIO",
		Envelope: TokenEnvelope{
			Capabilities: []string{"egress", "fs:read"}, // wrong alpha order
		},
		RegistryKeyID: "registry-2026",
	}
	b, err := CanonicalizeToken(unsorted)
	if err != nil {
		t.Fatalf("canonicalize: %v", err)
	}
	// The line should be sorted alphabetically: egress,fs:read.
	if !strings.Contains(string(b), "envelope_capabilities=egress,fs:read") {
		t.Errorf("expected sorted capability list in canonical bytes, got:\n%s", b)
	}
}

// TestCanonicalize_NewlineTerminated — every line ends with \n; no trailing
// junk after the last field.
func TestCanonicalize_NewlineTerminated(t *testing.T) {
	tok := &Token{
		Schema:         "m3c-skill-capability/v1",
		TokenID:        "ct:01HZTESTTESTTESTTESTTESTTE",
		IssuedAt:       "2026-05-10T00:00:00Z",
		ExpiresAt:      "2026-05-10T00:05:00Z",
		BundleDigest:   "sha256:abc",
		SkillName:      "demo",
		SkillVersion:   "0.1.0",
		CallerIdentity: "id:tester",
		CallerSession:  "sess:01HZSESSIONSESSIONSESSIO",
		RegistryKeyID:  "registry-2026",
	}
	b, err := CanonicalizeToken(tok)
	if err != nil {
		t.Fatalf("canonicalize: %v", err)
	}
	if len(b) == 0 || b[len(b)-1] != '\n' {
		t.Errorf("expected canonical bytes to end with \\n, got tail=%q", b[max(0, len(b)-10):])
	}
	// No double newlines (would indicate stray empty line):
	if strings.Contains(string(b), "\n\n") {
		t.Errorf("canonical bytes contain '\\n\\n': %q", b)
	}
}

// max helper for older Go versions; on 1.21+ this is a builtin.
func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// TestCanonicalize_MatchesPythonReference asserts byte-equality between the
// Go CanonicalizeToken output and a Python-issued reference vector. The
// fixture is the source of truth — regenerated by the Python script
// `flask/modules/skill_registry/tests/generate_canonical_fixture.py`,
// which mirrors the file into testdata/canonical_fixture.json. If this
// test diverges, the Go side is wrong (Python is the canonical reference).
//
// SPEC-0202 cross-language parity gate. Closes the install→invoke trust
// path: signatures issued by Python verify in Go iff their canonical bytes
// match byte-for-byte.
func TestCanonicalize_MatchesPythonReference(t *testing.T) {
	data, err := os.ReadFile("testdata/canonical_fixture.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fix struct {
		Token        map[string]any `json:"token"`
		CanonicalB64 string         `json:"canonical_b64"`
		CanonicalSHA string         `json:"canonical_sha256"`
	}
	if err := json.Unmarshal(data, &fix); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}

	// Reconstruct Token from the JSON via round-trip.
	tokBytes, err := json.Marshal(fix.Token)
	if err != nil {
		t.Fatalf("re-marshal token: %v", err)
	}
	var tok Token
	if err := json.Unmarshal(tokBytes, &tok); err != nil {
		t.Fatalf("unmarshal token: %v", err)
	}

	got, err := CanonicalizeToken(&tok)
	if err != nil {
		t.Fatalf("canonicalize: %v", err)
	}
	want, err := base64.StdEncoding.DecodeString(fix.CanonicalB64)
	if err != nil {
		t.Fatalf("decode canonical_b64: %v", err)
	}
	if !bytes.Equal(got, want) {
		gotSHA := sha256Hex(got)
		wantSHA := sha256Hex(want)
		t.Errorf(
			"canonical bytes diverge from Python reference\n"+
				"  python sha256: %s\n"+
				"  go     sha256: %s\n"+
				"  python length: %d\n"+
				"  go     length: %d",
			wantSHA, gotSHA, len(want), len(got),
		)
		// Print first divergent byte index for diagnostics.
		n := len(got)
		if len(want) < n {
			n = len(want)
		}
		for i := 0; i < n; i++ {
			if got[i] != want[i] {
				gotCtx := safeSlice(got, i-8, i+16)
				wantCtx := safeSlice(want, i-8, i+16)
				t.Errorf(
					"first divergence at byte %d:\n"+
						"  go     0x%02x in %q\n"+
						"  python 0x%02x in %q",
					i, got[i], gotCtx, want[i], wantCtx,
				)
				break
			}
		}
		// Also verify the published sha256 matches the reference bytes
		// (catches a corrupted fixture).
		if fix.CanonicalSHA != "" && fix.CanonicalSHA != wantSHA {
			t.Errorf(
				"fixture canonical_sha256 mismatch with its own canonical_b64: "+
					"declared=%s computed=%s — fixture is corrupt",
				fix.CanonicalSHA, wantSHA,
			)
		}
	}
}

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

func safeSlice(b []byte, lo, hi int) string {
	if lo < 0 {
		lo = 0
	}
	if hi > len(b) {
		hi = len(b)
	}
	return string(b[lo:hi])
}
