package skillgate

import (
	"bufio"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCanonicalize_PythonParity_Vectors asserts byte-identical
// canonicalization between the Python reference issuer (aims-core
// flask/modules/skill_registry/capability_tokens.py::_canonicalize_token_message)
// and the Go gateway implementation in CanonicalizeToken.
//
// Vectors are pre-generated by aims-core's tools/canonical_vectors_gen.py
// (run via `docker exec aims-core python3 ...`) into testdata/canonical-vectors.jsonl,
// one JSON object per line:
//
//	{"name": "...", "token": <wire-shape-token>, "expected_canonical_b64": "..."}
//
// Each token is the on-wire JSON shape (registry_signature_b64 left empty —
// the canonical message excludes the signature field).
//
// SPEC-0202 §4.1, §6, §15 D1.
//
// FAILURE MODE: if this test fails, signatures produced by the Python
// issuer will not verify in the Go gateway (or vice versa). DO NOT
// "fix" by adjusting either canonicalizer until you've identified
// which side is wrong against the schema/SPEC — both implementations
// are signed against by clients in the wild.
func TestCanonicalize_PythonParity_Vectors(t *testing.T) {
	path := filepath.Join("testdata", "canonical-vectors.jsonl")
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open vectors file: %v", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// JSONL lines can be long with full envelopes — bump the buffer.
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	count := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		count++
		var row struct {
			Name                 string          `json:"name"`
			Token                json.RawMessage `json:"token"`
			ExpectedCanonicalB64 string          `json:"expected_canonical_b64"`
		}
		if err := json.Unmarshal([]byte(line), &row); err != nil {
			t.Fatalf("vector %d: parse JSONL: %v", count, err)
		}

		t.Run(row.Name, func(t *testing.T) {
			var tok Token
			if err := json.Unmarshal(row.Token, &tok); err != nil {
				t.Fatalf("decode wire token: %v\nraw=%s", err, row.Token)
			}

			got, err := CanonicalizeToken(&tok)
			if err != nil {
				t.Fatalf("CanonicalizeToken: %v", err)
			}
			gotB64 := base64.StdEncoding.EncodeToString(got)

			if gotB64 != row.ExpectedCanonicalB64 {
				// Decode both for a readable diff.
				wantBytes, _ := base64.StdEncoding.DecodeString(row.ExpectedCanonicalB64)
				t.Errorf(
					"canonical bytes mismatch for vector %q\n"+
						"--- want (Python) %d bytes ---\n%s\n"+
						"--- got  (Go)    %d bytes ---\n%s\n"+
						"--- want b64 ---\n%s\n"+
						"--- got  b64 ---\n%s\n",
					row.Name,
					len(wantBytes), wantBytes,
					len(got), got,
					row.ExpectedCanonicalB64,
					gotB64,
				)
			}
		})
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scanner: %v", err)
	}
	if count == 0 {
		t.Fatal("no vectors loaded — testdata/canonical-vectors.jsonl is empty?")
	}
}
