package m3cproject

import (
	"os"
	"path/filepath"
	"testing"
)

const sampleDescriptor = `# .m3c/project.yaml — GENERATED by aims-core PLM (SPEC-0214). Do NOT edit by hand.
schema: m3c.project-descriptor/v1
spec: SPEC-0214

plm:
  project_id: kup-berlin-001
  name: KuP Berlin — Cohort 001
  client: K-U-P
  project_type: delivery
  status: active

repo:
  github_repo_url: https://github.com/kamir/m3c-tools-maintenance
  sync_target_path: NOTES

memory:
  tag_filter: [kup, kup-berlin-001]
  disable_filter: false

er1:
  target: local
  url: https://127.0.0.1:8081   # informational
  context: main

source:
  plm_doc_updated_at: 2026-05-12T08:01:44Z
  generated_at: 2026-05-12T07:40:14Z
  generated_by: aims-core/plm@deadbee
  commit_sha: null
`

func TestLoad_NoDescriptor_FallsBackToDirSlug(t *testing.T) {
	dir := t.TempDir()
	sub := filepath.Join(dir, "Some Project Dir")
	if err := os.MkdirAll(sub, 0o755); err != nil {
		t.Fatal(err)
	}
	d, err := Load(sub)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDirSlug {
		t.Fatalf("IDSource = %q, want %q", d.IDSource, SourceDirSlug)
	}
	if d.Plm.ProjectID != "Some-Project-Dir" {
		t.Fatalf("ProjectID = %q, want Some-Project-Dir", d.Plm.ProjectID)
	}
	if d.EffectiveER1Target() != "prod" || d.EffectiveER1Context() != "main" {
		t.Fatalf("defaults wrong: target=%q context=%q", d.EffectiveER1Target(), d.EffectiveER1Context())
	}
	if d.FoundPath != "" {
		t.Fatalf("FoundPath should be empty when no descriptor, got %q", d.FoundPath)
	}
}

func TestLoad_ParsesDescriptor_FromAncestor(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"), []byte(sampleDescriptor), 0o644); err != nil {
		t.Fatal(err)
	}
	deep := filepath.Join(root, "a", "b", "c")
	if err := os.MkdirAll(deep, 0o755); err != nil {
		t.Fatal(err)
	}
	d, err := Load(deep)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDescriptor {
		t.Fatalf("IDSource = %q, want descriptor", d.IDSource)
	}
	if d.Plm.ProjectID != "kup-berlin-001" {
		t.Fatalf("ProjectID = %q", d.Plm.ProjectID)
	}
	if d.Plm.Client != "K-U-P" || d.Plm.Status != "active" {
		t.Fatalf("identity parse wrong: client=%q status=%q", d.Plm.Client, d.Plm.Status)
	}
	if d.EffectiveER1Target() != "local" {
		t.Fatalf("er1 target = %q, want local", d.EffectiveER1Target())
	}
	if d.Repo.GithubRepoURL != "https://github.com/kamir/m3c-tools-maintenance" {
		t.Fatalf("repo url = %q", d.Repo.GithubRepoURL)
	}
	if len(d.Memory.TagFilter) != 2 || d.Memory.TagFilter[0] != "kup" {
		t.Fatalf("tag_filter = %v", d.Memory.TagFilter)
	}
	if d.Source.PLMDocUpdatedAt != "2026-05-12T08:01:44Z" {
		t.Fatalf("plm_doc_updated_at = %q", d.Source.PLMDocUpdatedAt)
	}
	if d.FoundPath == "" {
		t.Fatal("FoundPath should be set")
	}
}

func TestLoad_MalformedDescriptor_FallsBackToDirSlug(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	// valid YAML but no project_id
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"),
		[]byte("schema: m3c.project-descriptor/v1\nplm:\n  name: x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	d, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDirSlug {
		t.Fatalf("IDSource = %q, want dir-slug for a descriptor missing project_id", d.IDSource)
	}
	if d.Plm.ProjectID == "" {
		t.Fatal("ProjectID must not be empty")
	}
}

func TestDirSlug(t *testing.T) {
	cases := map[string]string{
		"/x/y/m3c-tools-maintenance": "m3c-tools-maintenance",
		"/x/y/My Project!":           "My-Project",
		"/":                          "unknown-project",
	}
	for in, want := range cases {
		if got := DirSlug(in); got != want {
			t.Errorf("DirSlug(%q) = %q, want %q", in, got, want)
		}
	}
}
