package m3cproject

import (
	"os"
	"path/filepath"
	"testing"
)

const sampleDescriptor = `# .m3c/project.yaml — GENERATED by aims-core PLM (SPEC-0214). Do NOT edit by hand.
schema: m3c.project-descriptor/v1
spec: SPEC-0214

plm:
  project_id: kup-berlin-001
  name: KuP Berlin — Cohort 001
  client: K-U-P
  project_type: delivery
  status: active

repo:
  github_repo_url: https://github.com/kamir/m3c-tools-maintenance
  sync_target_path: NOTES

memory:
  tag_filter: [kup, kup-berlin-001]
  disable_filter: false

er1:
  target: local
  url: https://127.0.0.1:8081   # informational
  context: main

source:
  plm_doc_updated_at: 2026-05-12T08:01:44Z
  generated_at: 2026-05-12T07:40:14Z
  generated_by: aims-core/plm@deadbee
  commit_sha: null
`

func TestLoad_NoDescriptor_FallsBackToDirSlug(t *testing.T) {
	dir := t.TempDir()
	sub := filepath.Join(dir, "Some Project Dir")
	if err := os.MkdirAll(sub, 0o755); err != nil {
		t.Fatal(err)
	}
	d, err := Load(sub)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDirSlug {
		t.Fatalf("IDSource = %q, want %q", d.IDSource, SourceDirSlug)
	}
	if d.Plm.ProjectID != "Some-Project-Dir" {
		t.Fatalf("ProjectID = %q, want Some-Project-Dir", d.Plm.ProjectID)
	}
	if d.EffectiveER1Target() != "prod" || d.EffectiveER1Context() != "main" {
		t.Fatalf("defaults wrong: target=%q context=%q", d.EffectiveER1Target(), d.EffectiveER1Context())
	}
	if d.FoundPath != "" {
		t.Fatalf("FoundPath should be empty when no descriptor, got %q", d.FoundPath)
	}
}

func TestLoad_ParsesDescriptor_FromAncestor(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"), []byte(sampleDescriptor), 0o644); err != nil {
		t.Fatal(err)
	}
	deep := filepath.Join(root, "a", "b", "c")
	if err := os.MkdirAll(deep, 0o755); err != nil {
		t.Fatal(err)
	}
	d, err := Load(deep)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDescriptor {
		t.Fatalf("IDSource = %q, want descriptor", d.IDSource)
	}
	if d.Plm.ProjectID != "kup-berlin-001" {
		t.Fatalf("ProjectID = %q", d.Plm.ProjectID)
	}
	if d.Plm.Client != "K-U-P" || d.Plm.Status != "active" {
		t.Fatalf("identity parse wrong: client=%q status=%q", d.Plm.Client, d.Plm.Status)
	}
	if d.EffectiveER1Target() != "local" {
		t.Fatalf("er1 target = %q, want local", d.EffectiveER1Target())
	}
	if d.Repo.GithubRepoURL != "https://github.com/kamir/m3c-tools-maintenance" {
		t.Fatalf("repo url = %q", d.Repo.GithubRepoURL)
	}
	if len(d.Memory.TagFilter) != 2 || d.Memory.TagFilter[0] != "kup" {
		t.Fatalf("tag_filter = %v", d.Memory.TagFilter)
	}
	if d.Source.PLMDocUpdatedAt != "2026-05-12T08:01:44Z" {
		t.Fatalf("plm_doc_updated_at = %q", d.Source.PLMDocUpdatedAt)
	}
	if d.FoundPath == "" {
		t.Fatal("FoundPath should be set")
	}
}

func TestLoad_MalformedDescriptor_FallsBackToDirSlug(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	// valid YAML but no project_id
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"),
		[]byte("schema: m3c.project-descriptor/v1\nplm:\n  name: x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	d, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.IDSource != SourceDirSlug {
		t.Fatalf("IDSource = %q, want dir-slug for a descriptor missing project_id", d.IDSource)
	}
	if d.Plm.ProjectID == "" {
		t.Fatal("ProjectID must not be empty")
	}
}

const sampleDescriptorV2 = `# .m3c/project.yaml — GENERATED by aims-core PLM (SPEC-0214).
schema: m3c.project-descriptor/v2
spec: SPEC-0214

plm:
  project_id: kup-berlin-001
  name: KuP Berlin
  client: K-U-P
  status: active

repo:
  github_repo_url: https://github.com/kamir/m3c-tools-maintenance
  sync_target_path: NOTES

memory:
  tag_filter: [kup]
  disable_filter: false

er1:
  target: prod
  context: main

channels:   # SPEC-0217 — typed bindings to external surfaces (non-retired)
  - {id: ch_aaaa1111, kind: git-repo, ref: https://github.com/kamir/m3c-tools-maintenance, label: main repo, role: primary, mode: sync-push}
  - {id: ch_bbbb2222, kind: er1-context, ref: er1://prod/main, label: ER1 memory context, role: primary, mode: read-on-demand}
  - {id: ch_cccc3333, kind: gdrive-folder, ref: https://drive.google.com/drive/folders/F1, label: Drive folder, role: secondary, mode: reference}

source:
  plm_doc_updated_at: 2026-05-12T08:01:44Z
  generated_at: 2026-05-12T07:40:14Z
  generated_by: aims-core/plm@deadbee
  commit_sha: null
`

func TestLoad_ParsesV2ChannelsBlock(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"), []byte(sampleDescriptorV2), 0o644); err != nil {
		t.Fatal(err)
	}
	d, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.Schema != SchemaV2 || !KnownSchema(d.Schema) {
		t.Fatalf("schema = %q (KnownSchema=%v), want v2/known", d.Schema, KnownSchema(d.Schema))
	}
	if d.IDSource != SourceDescriptor || d.Plm.ProjectID != "kup-berlin-001" {
		t.Fatalf("id resolution wrong: source=%q id=%q", d.IDSource, d.Plm.ProjectID)
	}
	if len(d.Channels) != 3 {
		t.Fatalf("channels = %d, want 3: %+v", len(d.Channels), d.Channels)
	}
	repo := d.Channels[0]
	if repo.Kind != "git-repo" || repo.Role != "primary" || repo.Mode != "sync-push" ||
		repo.Ref != "https://github.com/kamir/m3c-tools-maintenance" || repo.Label != "main repo" {
		t.Fatalf("git-repo channel parsed wrong: %+v", repo)
	}
	if d.Channels[1].Kind != "er1-context" || d.Channels[1].Ref != "er1://prod/main" {
		t.Fatalf("er1-context channel parsed wrong: %+v", d.Channels[1])
	}
	if d.Channels[2].Kind != "gdrive-folder" || d.Channels[2].Role != "secondary" {
		t.Fatalf("gdrive channel parsed wrong: %+v", d.Channels[2])
	}
}

func TestKnownSchema(t *testing.T) {
	for _, s := range []string{SchemaV1, SchemaV2, " m3c.project-descriptor/v1 "} {
		if !KnownSchema(s) {
			t.Errorf("KnownSchema(%q) = false, want true", s)
		}
	}
	for _, s := range []string{"", "m3c.project-descriptor/v3", "garbage"} {
		if KnownSchema(s) {
			t.Errorf("KnownSchema(%q) = true, want false", s)
		}
	}
}

func TestLoad_V1DescriptorHasNoChannels(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".m3c"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".m3c", "project.yaml"), []byte(sampleDescriptor), 0o644); err != nil {
		t.Fatal(err)
	}
	d, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(d.Channels) != 0 {
		t.Fatalf("v1 descriptor should have no channels, got %d", len(d.Channels))
	}
	// v1 is still a known schema and resolves fine
	if !KnownSchema(d.Schema) || d.IDSource != SourceDescriptor {
		t.Fatalf("v1 should be known + descriptor-sourced: schema=%q source=%q", d.Schema, d.IDSource)
	}
}

func TestDirSlug(t *testing.T) {
	cases := map[string]string{
		"/x/y/m3c-tools-maintenance": "m3c-tools-maintenance",
		"/x/y/My Project!":           "My-Project",
		"/":                          "unknown-project",
	}
	for in, want := range cases {
		if got := DirSlug(in); got != want {
			t.Errorf("DirSlug(%q) = %q, want %q", in, got, want)
		}
	}
}
