package report

// FR-0472: the report as one self-contained page. These tests hold down the
// four prohibitions of the FR: no judgement, no claim about validity that was
// not checked, no reduction of the eight status words, no external resource.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"html"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/kamir/m3c-tools/pkg/skillctl/trustfreeze"
)

// htmlTestGenerator is the rendering version the goldens are pinned to.
const htmlTestGenerator = "0.0.0-test"

func TestCaptureReportHTMLGolden(t *testing.T) {
	r := kindReport(t, trustfreeze.KindCapture)
	got, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	checkGolden(t, "report_capture.html.golden", got)
}

func TestBaselineReportHTMLGolden(t *testing.T) {
	r := kindReport(t, trustfreeze.KindBaseline)
	got, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	checkGolden(t, "report_baseline.html.golden", got)
}

func TestDiffReportHTMLGolden(t *testing.T) {
	r := kindReport(t, trustfreeze.KindDiff)
	got, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	checkGolden(t, "report_diff.html.golden", got)
}

func TestCaptureCapabilitiesHTMLGolden(t *testing.T) {
	b := writeCaptureWith(t, t.TempDir(), "capture", trustfreeze.KindCapture, testTime, "24.04", 0, capabilitiesFixture())
	r, err := FromBundle(b)
	if err != nil {
		t.Fatal(err)
	}
	got, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	checkGolden(t, "report_capture_capabilities.html.golden", got)
}

// TestReportHTMLTwiceTheSameBytes: the page of one report is the same bytes
// every time, so two printouts of the same bundle are comparable.
func TestReportHTMLTwiceTheSameBytes(t *testing.T) {
	for _, r := range everyKindOfReport(t) {
		first, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
		if err != nil {
			t.Fatal(err)
		}
		for i := 0; i < 8; i++ {
			again, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(first, again) {
				t.Fatalf("%s: run %d differs from the first run", r.Input.Kind, i+2)
			}
		}
	}
}

// TestReportHTMLHasNoExternalReference: the page opens on a host without a
// network, so it names no address, loads no script, no stylesheet and no font,
// and carries no data URI. The check reads the generated bytes, not the
// template: a template can be clean and a value carry an address into it.
func TestReportHTMLHasNoExternalReference(t *testing.T) {
	for _, r := range everyKindOfReport(t) {
		page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
		if err != nil {
			t.Fatal(err)
		}
		if found := externalReferences(string(page)); len(found) > 0 {
			t.Fatalf("%s: the page carries %d external reference(s):\n%s",
				r.Input.Kind, len(found), strings.Join(found, "\n"))
		}
		// No attribute of that class at all, jump target included: the page
		// has no links.
		if n := len(attributeNames(string(page), "href", "src")); n > 0 {
			t.Fatalf("%s: the page carries %d href/src attribute(s)", r.Input.Kind, n)
		}
	}
}

// TestExternalReferenceCheckFindsAPlantedReference is the counter-probe: a
// check that only ever runs against the real page proves that it can be green,
// not that it can search. Each planted reference must be found, and the one
// allowed form (a jump target inside the document) must not.
func TestExternalReferenceCheckFindsAPlantedReference(t *testing.T) {
	page, err := MarshalHTML(kindReport(t, trustfreeze.KindCapture), HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	base := string(page)
	if found := externalReferences(base); len(found) > 0 {
		t.Fatalf("the page is not clean to begin with: %v", found)
	}
	for _, tc := range []struct {
		name    string
		planted string
		where   string
	}{
		{"a stylesheet link", `<link rel="stylesheet" href="https://example.invalid/a.css">`, "</head>"},
		{"a script element", `<script src="https://example.invalid/d.js"></script>`, "</head>"},
		{"an at-import in the style block", "@import url(\"https://example.invalid/b.css\");\n", "</style>"},
		{"a url() in the style block", "body { background: url(https://example.invalid/c.png); }\n", "</style>"},
		{"an inline style with a url()", `<div style="background: url(https://example.invalid/e.png)"></div>`, "</body>"},
		{"a data URI image", `<img src="data:image/png;base64,iVBORw0KGgo=">`, "</body>"},
		{"a web font in the style block", "@font-face { font-family: x; src: url(x.woff2); }\n", "</style>"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			at := strings.Index(base, tc.where)
			if at < 0 {
				t.Fatalf("the page has no %s to plant before", tc.where)
			}
			planted := base[:at] + tc.planted + base[at:]
			if found := externalReferences(planted); len(found) == 0 {
				t.Fatalf("the check did not find the planted %s", tc.planted)
			}
		})
	}
	t.Run("a jump target inside the document is allowed", func(t *testing.T) {
		at := strings.Index(base, "</body>")
		planted := base[:at] + `<a href="#state">state</a>` + base[at:]
		if found := externalReferences(planted); len(found) > 0 {
			t.Fatalf("a jump target inside the document was refused: %v", found)
		}
	})
}

// TestReportHTMLShowsHostileContentAsText: a value out of a host that looks
// like an address or like markup is content, not a reference. The page shows
// it, escaped, and the external-reference check stays green. This is the same
// statement from the other side: the check reads markup, not strings.
func TestReportHTMLShowsHostileContentAsText(t *testing.T) {
	const addr = "https://boese.invalid/x"
	const markup = "<script>alert(1)</script>"
	r := reportWithAttributes(map[string]string{"os_family": "linux"})
	r.Capture.Probes = []trustfreeze.ProbeSummary{{
		ProbeID: "linux.motd", Status: trustfreeze.StatusPartial,
		Reason: "the banner could not be read in full: " + markup + " " + addr,
	}}
	r.Capture.Capabilities = &CapabilitiesSection{
		Resolver: "linux.privilege/v1",
		Capabilities: []CapabilityLine{{
			ID: "capability/execute/host/user/alice", SubjectID: "user/alice",
			Action: "execute", Resource: "host", Effect: "allowed", Privilege: "user",
			Attributes: map[string]string{"homepage": addr, "banner": markup},
			Sources:    []string{"file:/etc/sudoers"},
		}},
		Diagnostics: []trustfreeze.Diagnostic{{Code: "privilege_source_unreadable", Field: addr, Message: markup}},
	}
	page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	s := string(page)
	if found := externalReferences(s); len(found) > 0 {
		t.Fatalf("content was mistaken for a reference: %v", found)
	}
	if strings.Contains(s, markup) {
		t.Fatal("the page carries an unescaped <script> element from a host value")
	}
	if n := strings.Count(s, "&lt;script&gt;alert(1)&lt;/script&gt;"); n < 3 {
		t.Fatalf("the markup-looking value is on the page %d times as escaped text, want at least 3", n)
	}
	if n := strings.Count(s, addr); n < 3 {
		t.Fatalf("the address-looking value is on the page %d times, want at least 3: content must not be dropped", n)
	}
}

// TestReportHTMLKeepsEveryStatusWordAndItsReason: the eight status words stay
// words, and every probe that carries a reason has that reason beside it in
// full. The third prohibition of the FR: two coloured dots would throw away
// what the capture paid to collect.
func TestReportHTMLKeepsEveryStatusWordAndItsReason(t *testing.T) {
	r := reportWithEveryStatus()
	page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	text := html.UnescapeString(string(page))
	var missing []string
	for _, s := range trustfreeze.ProbeStatuses() {
		if !strings.Contains(text, string(s)) {
			missing = append(missing, string(s))
		}
	}
	if len(missing) > 0 {
		t.Fatalf("the page does not name these status words: %s", strings.Join(missing, ", "))
	}
	if lost := reasonsNotOnPage(text, r.Capture.Probes); len(lost) > 0 {
		t.Fatalf("%d reason(s) are not on the page in full:\n%s", len(lost), strings.Join(lost, "\n"))
	}
}

// TestReasonCheckFindsATruncatedReason is the counter-probe to the test above:
// a page that shortens a reason must make the check red.
func TestReasonCheckFindsATruncatedReason(t *testing.T) {
	r := reportWithEveryStatus()
	page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	text := html.UnescapeString(string(page))
	long := ""
	for _, p := range r.Capture.Probes {
		if len(p.Reason) > 16 {
			long = p.Reason
			break
		}
	}
	if long == "" {
		t.Fatal("the fixture has no reason long enough to shorten")
	}
	truncated := strings.ReplaceAll(text, long, long[:12])
	lost := reasonsNotOnPage(truncated, r.Capture.Probes)
	if len(lost) == 0 {
		t.Fatal("the check did not see the shortened reason")
	}
	if !strings.Contains(strings.Join(lost, "\n"), long) {
		t.Fatalf("the check does not name the reason it misses: %v", lost)
	}
}

// TestReportHTMLShowsTheDigestsOfTheProjection: every digest of the JSON is on
// the page, in groups of eight characters, and removing the separators gives
// the value back unchanged.
func TestReportHTMLShowsTheDigestsOfTheProjection(t *testing.T) {
	for _, r := range everyKindOfReport(t) {
		page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
		if err != nil {
			t.Fatal(err)
		}
		raw, err := Marshal(r)
		if err != nil {
			t.Fatal(err)
		}
		want := digestsOfJSON(t, raw)
		if len(want) == 0 {
			t.Fatalf("%s: the report carries no digest, the test proves nothing", r.Input.Kind)
		}
		text := html.UnescapeString(string(page))
		for path, value := range want {
			grouped := groupDigest(value)
			if !strings.Contains(text, grouped) {
				t.Fatalf("%s: %s is not on the page as %q", r.Input.Kind, path, grouped)
			}
			if bare := strings.ReplaceAll(grouped, " ", ""); bare != value {
				t.Fatalf("%s: the grouping changed the value: %q is not %q", r.Input.Kind, bare, value)
			}
		}
	}
}

// TestReportHTMLCarriesTheGuidanceOfItsKind: the guidance exists per bundle
// kind, and the command it names fits that kind. A capture carries no
// signature, so its guidance names no trusted key.
func TestReportHTMLCarriesTheGuidanceOfItsKind(t *testing.T) {
	for _, tc := range []struct {
		kind    trustfreeze.Kind
		wants   []string
		unwants []string
	}{
		{
			kind: trustfreeze.KindCapture,
			wants: []string{
				"A record of what one machine looked like at one moment.",
				"skillctl trust-freeze baseline approve --capture <bundle>",
				"skillctl trust-freeze verify --bundle <bundle>",
			},
			// A capture is not signed, so nothing here takes a key.
			unwants: []string{"--trusted-key"},
		},
		{
			kind: trustfreeze.KindBaseline,
			wants: []string{
				"An approved state.",
				"skillctl trust-freeze verify --bundle <bundle> --trusted-key <public key>",
				"skillctl trust-freeze diff --baseline <baseline> --current <capture> --trusted-key <public key>",
			},
		},
		{
			kind: trustfreeze.KindDiff,
			wants: []string{
				"The difference between an approved baseline and a later capture of the same",
				"skillctl trust-freeze diff --baseline <baseline> --current <capture> --trusted-key <public key>",
			},
			unwants: []string{"skillctl trust-freeze baseline approve --capture"},
		},
	} {
		t.Run(string(tc.kind), func(t *testing.T) {
			page, err := MarshalHTML(kindReport(t, tc.kind), HTMLOptions{Generator: htmlTestGenerator})
			if err != nil {
				t.Fatal(err)
			}
			text := html.UnescapeString(string(page))
			for _, w := range tc.wants {
				if !strings.Contains(text, w) {
					t.Fatalf("the page does not carry %q", w)
				}
			}
			for _, u := range tc.unwants {
				if strings.Contains(text, u) {
					t.Fatalf("the page of a %s carries %q", tc.kind, u)
				}
			}
			for _, heading := range []string{"What this is", "What it answers", "What it does not answer", "What to do next"} {
				if !strings.Contains(text, heading) {
					t.Fatalf("the guidance has no %q section", heading)
				}
			}
		})
	}
}

// TestReportHTMLClaimsNoValidity: the second and heaviest prohibition of the
// FR. A baseline page quotes the signature section of the projection and names
// the command that evaluates it; it says nowhere that anything is valid,
// trusted or verified.
func TestReportHTMLClaimsNoValidity(t *testing.T) {
	page, err := MarshalHTML(kindReport(t, trustfreeze.KindBaseline), HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	text := html.UnescapeString(string(page))
	for _, want := range []string{SignatureNotEvaluated, SignatureVerifyWith} {
		if !strings.Contains(text, want) {
			t.Fatalf("the page does not quote %q", want)
		}
	}
	if found := validityClaims(text); len(found) > 0 {
		t.Fatalf("the page claims validity:\n%s", strings.Join(found, "\n"))
	}
}

// TestValidityClaimCheckFindsAPlantedClaim is the counter-probe: the forbidden
// list has to find a planted sentence, otherwise its silence means nothing.
func TestValidityClaimCheckFindsAPlantedClaim(t *testing.T) {
	for _, planted := range []string{
		"signature: valid",
		"The signature is valid.",
		"This baseline is trusted.",
		"signature verified against the trusted key",
		"Die Signatur ist gueltig.",
	} {
		if found := validityClaims("the page says: " + planted); len(found) == 0 {
			t.Fatalf("the check did not find %q", planted)
		}
	}
}

// TestReportHTMLSaysWhatItDoesNotShow: the page shows the artifacts only as a
// count, and it says so, with the number from the projection and the command
// that shows them. What is left out is named as left out.
func TestReportHTMLSaysWhatItDoesNotShow(t *testing.T) {
	r := kindReport(t, trustfreeze.KindCapture)
	page, err := MarshalHTML(r, HTMLOptions{Generator: htmlTestGenerator})
	if err != nil {
		t.Fatal(err)
	}
	text := html.UnescapeString(string(page))
	n := len(r.Capture.Artifacts)
	if n == 0 {
		t.Fatal("the fixture has no artifact, the test proves nothing")
	}
	if !strings.Contains(text, fmt.Sprintf("%d", n)) {
		t.Fatalf("the page does not name the number of artifacts (%d)", n)
	}
	for _, want := range []string{"Not on this page", "skillctl trust-freeze report --input"} {
		if !strings.Contains(text, want) {
			t.Fatalf("the page does not carry %q", want)
		}
	}
}

// --- checks ------------------------------------------------------------------

// htmlTagPattern matches one tag of the markup. Data can never produce a tag:
// html/template escapes "<" in every value it writes, which the hostile-content
// test measures.
var htmlTagPattern = regexp.MustCompile(`<[^>]*>`)

// htmlAttrPattern matches one attribute inside a tag.
var htmlAttrPattern = regexp.MustCompile(`([A-Za-z_:][-\w:.]*)\s*=\s*("([^"]*)"|'([^']*)'|([^\s"'>]+))`)

// htmlLoadingAttrs are the attributes that make a browser fetch something.
var htmlLoadingAttrs = map[string]bool{
	"src": true, "srcset": true, "integrity": true, "background": true,
	"poster": true, "codebase": true, "xlink:href": true, "formaction": true,
	"action": true, "data": true, "manifest": true, "ping": true,
}

// htmlLoadingTags are the elements that pull something in.
var htmlLoadingTags = map[string]bool{
	"script": true, "iframe": true, "object": true, "embed": true, "link": true,
	"base": true, "applet": true, "frame": true, "frameset": true, "img": true,
	"audio": true, "video": true, "source": true, "track": true, "portal": true,
}

// externalReferences returns every external reference of a page. It reads the
// markup and the content of the style blocks, never a text node: an attribute
// value that contains an address is content and has to be shown, escaped.
// Allowed is exactly one form, a jump target inside the document (href="#...").
func externalReferences(page string) []string {
	var found []string
	for _, tag := range htmlTagPattern.FindAllString(page, -1) {
		name := strings.ToLower(strings.TrimLeft(strings.Fields(strings.Trim(tag, "<>/"))[0], "/"))
		if htmlLoadingTags[name] {
			found = append(found, "element <"+name+">: "+tag)
		}
		for _, m := range htmlAttrPattern.FindAllStringSubmatch(tag, -1) {
			attr := strings.ToLower(m[1])
			value := m[3] + m[4] + m[5]
			switch {
			case attr == "href" && strings.HasPrefix(value, "#"):
				// A jump target inside the document, the one allowed form.
			case attr == "href" || htmlLoadingAttrs[attr]:
				found = append(found, "attribute "+attr+"="+value)
			case strings.Contains(value, "://") || strings.HasPrefix(value, "//") ||
				strings.Contains(strings.ToLower(value), "url(") ||
				regexp.MustCompile(`(?i)^(data|file|javascript|vbscript):`).MatchString(value):
				found = append(found, "attribute "+attr+" carries a reference: "+value)
			}
		}
	}
	for _, style := range styleBlocks(page) {
		lower := strings.ToLower(style)
		for _, bad := range []string{"@import", "@font-face", "url(", "://"} {
			if strings.Contains(lower, bad) {
				found = append(found, "style block carries "+bad)
			}
		}
	}
	return found
}

// styleBlocks returns the content of every <style> element of a page.
func styleBlocks(page string) []string {
	var out []string
	rest := page
	for {
		open := strings.Index(strings.ToLower(rest), "<style")
		if open < 0 {
			return out
		}
		start := strings.Index(rest[open:], ">")
		if start < 0 {
			return out
		}
		start += open + 1
		end := strings.Index(strings.ToLower(rest[start:]), "</style")
		if end < 0 {
			return append(out, rest[start:])
		}
		out = append(out, rest[start:start+end])
		rest = rest[start+end:]
	}
}

// attributeNames returns every occurrence of the named attributes in the
// markup of a page.
func attributeNames(page string, names ...string) []string {
	want := map[string]bool{}
	for _, n := range names {
		want[n] = true
	}
	var out []string
	for _, tag := range htmlTagPattern.FindAllString(page, -1) {
		for _, m := range htmlAttrPattern.FindAllStringSubmatch(tag, -1) {
			if want[strings.ToLower(m[1])] {
				out = append(out, m[0])
			}
		}
	}
	return out
}

// validityClaimPatterns are sentences that would claim a signature, a key or a
// bundle is valid. report projects and evaluates nothing, so none of them may
// appear. The word "verify" on its own is allowed: the page names the command
// that does evaluate, which is the opposite of a claim.
var validityClaimPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)signature[^.\n]{0,40}\bis valid\b`),
	regexp.MustCompile(`(?i)signature\s*[:=]\s*valid\b`),
	regexp.MustCompile(`(?i)\bsigned and valid\b`),
	regexp.MustCompile(`(?i)\bvalid signature\b`),
	regexp.MustCompile(`(?i)\bsignature verified\b`),
	regexp.MustCompile(`(?i)\bverified against\b`),
	regexp.MustCompile(`(?i)\bis (?:valid|trusted|authentic|genuine)\b`),
	regexp.MustCompile(`(?i)\bist g(?:ue|.)ltig\b`),
}

// validityClaimNegations are the words that turn one of the patterns above
// into the opposite of a claim: "Whether the signature is valid" is the
// sentence the guidance is required to carry, and "the signature is valid" is
// the sentence it must never carry.
var validityClaimNegations = []string{"whether", "not ", "cannot", "never", "nor ", "unless", "no "}

// validityClaims returns every claim about validity found in a text. A match
// whose immediate context negates or questions it is not a claim.
func validityClaims(text string) []string {
	var found []string
	for _, re := range validityClaimPatterns {
		for _, at := range re.FindAllStringIndex(text, -1) {
			from := at[0] - 28
			if from < 0 {
				from = 0
			}
			before := strings.ToLower(text[from:at[0]])
			negated := false
			for _, n := range validityClaimNegations {
				if strings.Contains(before, n) {
					negated = true
					break
				}
			}
			if !negated {
				found = append(found, re.String()+": "+text[at[0]:at[1]])
			}
		}
	}
	sort.Strings(found)
	return found
}

// reasonsNotOnPage returns, by name, the probe reasons that are not on the page
// in full.
func reasonsNotOnPage(text string, probes []trustfreeze.ProbeSummary) []string {
	var out []string
	for _, p := range probes {
		if p.Reason == "" {
			continue
		}
		if !strings.Contains(text, p.Reason) {
			out = append(out, fmt.Sprintf("%s (%s): %q", p.ProbeID, p.Status, p.Reason))
		}
	}
	return out
}

// digestsOfJSON returns every digest-shaped value of a report, by field path.
func digestsOfJSON(t *testing.T, raw []byte) map[string]string {
	t.Helper()
	var tree any
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&tree); err != nil {
		t.Fatal(err)
	}
	out := map[string]string{}
	var walk func(path string, v any)
	walk = func(path string, v any) {
		switch node := v.(type) {
		case map[string]any:
			for k, e := range node {
				// The digests of the visible sections only: a per-artifact or
				// per-change digest is not on the page, by decision.
				if k == "artifacts" || k == "probe_results" || k == "changes" || k == "findings" {
					continue
				}
				walk(path+"."+k, e)
			}
		case []any:
			for i, e := range node {
				walk(fmt.Sprintf("%s[%d]", path, i), e)
			}
		case string:
			if strings.HasPrefix(node, "sha256:") {
				out[path] = node
			}
		}
	}
	walk("", tree)
	return out
}

// --- fixtures ----------------------------------------------------------------

// kindReport returns the report of one synthetic bundle per kind.
func kindReport(t *testing.T, kind trustfreeze.Kind) Report {
	t.Helper()
	dir := t.TempDir()
	if kind == trustfreeze.KindDiff {
		_, _, d, v := scenario(t, dir)
		r, err := FromBundle(writeDiffBundle(t, dir, d, &v))
		if err != nil {
			t.Fatal(err)
		}
		return r
	}
	b := writeCapture(t, dir, "bundle", kind, testTime, "24.04", 0)
	r, err := FromBundle(b)
	if err != nil {
		t.Fatal(err)
	}
	return r
}

// reportWithEveryStatus is a capture report whose probes cover all eight status
// words, each one with the reason that belongs to it.
func reportWithEveryStatus() Report {
	reasons := map[trustfreeze.ProbeStatus]string{
		trustfreeze.StatusCaptured:         "",
		trustfreeze.StatusPartial:          "read 2 of 3 sudoers files; the rule set on this host is incomplete in this document",
		trustfreeze.StatusUnsupported:      trustfreeze.ReasonNotImplemented,
		trustfreeze.StatusUnavailable:      "the tool this probe needs is not installed on this host",
		trustfreeze.StatusPermissionDenied: "permission denied reading the ssh server state",
		trustfreeze.StatusTimeout:          "the probe did not finish within its budget of 5000 ms",
		trustfreeze.StatusFailed:           "the tool exited with code 1 and wrote nothing to standard output",
		trustfreeze.StatusNotApplicable:    "this operating system has no such feature",
	}
	var probes []trustfreeze.ProbeSummary
	var gaps []trustfreeze.CompletenessGap
	for _, s := range trustfreeze.ProbeStatuses() {
		id := "probe." + string(s)
		probes = append(probes, trustfreeze.ProbeSummary{ProbeID: id, Status: s, Reason: reasons[s]})
		if s != trustfreeze.StatusCaptured {
			gaps = append(gaps, trustfreeze.CompletenessGap{ProbeID: id, Status: s, Reason: trustfreeze.GapNotCaptured})
		}
	}
	r := reportWithAttributes(map[string]string{"os_family": "linux"})
	r.Capture.Probes = probes
	r.Capture.Completeness = trustfreeze.Completeness{
		Status:   trustfreeze.CompletenessIncomplete,
		Required: []string{"probe.captured", "probe.timeout"},
		Gaps:     gaps,
	}
	return r
}

// TestReportPackageReadsNoClock: the projection and its renderings must not
// depend on the time of rendering, so the page of an unchanged bundle has the
// same bytes today and next year. The package therefore imports no clock.
// Measured over the import lists of its own non-test files.
func TestReportPackageReadsNoClock(t *testing.T) {
	set := token.NewFileSet()
	pkgs, err := parser.ParseDir(set, ".", func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ImportsOnly)
	if err != nil {
		t.Fatal(err)
	}
	files := 0
	for _, pkg := range pkgs {
		for name, f := range pkg.Files {
			files++
			for _, imp := range f.Imports {
				if imp.Path.Value == `"time"` {
					t.Fatalf("%s imports time: a projection that reads a clock is not reproducible", name)
				}
			}
		}
	}
	// The walk must have seen the files, otherwise it proves nothing.
	if files < 3 {
		t.Fatalf("the walk saw %d non-test file(s) of the package", files)
	}
}
