package main

// End-to-end wiring test for Welle-1 Befund 1.5: `skillctl pin generate
// --require-local-audit` must emit a PreToolUse gate command that actually
// CONSUMES gateRequireLocalAudit. Before the fix it emitted `verify-hook`
// (which never reads the flag) next to skillctlRequireLocalAudit:true, so the
// generated enterprise lockdown never enforced the R-8.2 audit fail-close.
//
// The loop closed here: the real `pin generate` CLI writes the JSON; the test
// parses the gate command OUT OF THAT JSON; the managed-flag seams are wired to
// read THE GENERATED BYTES (not stubbed constants); the command's subcommand is
// dispatched exactly as main.go does; and the run happens in a throwaway HOME
// whose audit state dir is unwritable (outbox + spool + trail all fail, only
// the pre-materialized device key survives, so the sink IS reached). Expected:
// fail-closed deny carrying exit 26 with the flag, a silent allow without it.

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kamir/m3c-tools/pkg/skillctl/pin"
)

// generatePinSettings runs the real `pin generate` command runner with --out
// and returns the written managed-settings bytes.
func generatePinSettings(t *testing.T, extra ...string) []byte {
	t.Helper()
	out := filepath.Join(t.TempDir(), "managed-settings.json")
	args := append([]string{"--binary", "/usr/local/bin/skillctl", "--out", out}, extra...)
	var so, se bytes.Buffer
	if code := runPinGenerate(args, &so, &se); code != pinExitOK {
		t.Fatalf("pin generate %v exited %d: %s", args, code, se.String())
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// preToolUseCommandFromJSON returns the single PreToolUse(Skill) hook command
// from the generated settings.
func preToolUseCommandFromJSON(t *testing.T, settings []byte) string {
	t.Helper()
	var doc struct {
		Hooks struct {
			PreToolUse []struct {
				Matcher string `json:"matcher"`
				Hooks   []struct {
					Command string `json:"command"`
				} `json:"hooks"`
			} `json:"PreToolUse"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(settings, &doc); err != nil {
		t.Fatalf("unmarshal generated settings: %v\n%s", err, settings)
	}
	if len(doc.Hooks.PreToolUse) != 1 || len(doc.Hooks.PreToolUse[0].Hooks) != 1 {
		t.Fatalf("expected exactly one PreToolUse gate hook:\n%s", settings)
	}
	if m := doc.Hooks.PreToolUse[0].Matcher; m != "Skill" {
		t.Fatalf("gate matcher must be Skill, got %q", m)
	}
	return doc.Hooks.PreToolUse[0].Hooks[0].Command
}

// wireManagedSeamsFromBytes points every managed-settings seam at the GENERATED
// bytes, so the gate consumes the artifact's flags instead of the machine's
// real root-owned file (hermetic) or a stubbed constant (which would not prove
// the wiring).
func wireManagedSeamsFromBytes(t *testing.T, b []byte) {
	t.Helper()
	oe, orla := gateManagedEnterprise, gateRequireLocalAudit
	osgf, oram := gateStateGatesFallback, gateRequireAgentMandate
	gateManagedEnterprise = func() bool { return pin.EnterpriseFromBytes(b) }
	gateRequireLocalAudit = func() bool { return pin.RequireLocalAuditFromBytes(b) }
	gateStateGatesFallback = func() bool { return pin.StateGateFallbackFromBytes(b) }
	gateRequireAgentMandate = func() bool { return pin.RequireAgentMandateFromBytes(b) }
	t.Cleanup(func() {
		gateManagedEnterprise, gateRequireLocalAudit = oe, orla
		gateStateGatesFallback, gateRequireAgentMandate = osgf, oram
	})
}

// brokenAuditHome builds a throwaway HOME whose audit state dir
// (~/.claude/skillctl) is unwritable: outbox.db, spool.jsonl and the signed
// trail can not be created, but the device key already exists, so signing
// succeeds and the outbox sink is reached (the documented non-escalated gaps,
// key/sign failure, are deliberately NOT what this test exercises).
func brokenAuditHome(t *testing.T) {
	t.Helper()
	if os.Geteuid() == 0 {
		t.Skip("needs a non-root euid: mode 0500 does not stop root writes")
	}
	home := t.TempDir()
	t.Setenv("HOME", home)
	if _, err := invocationDeviceKey(home); err != nil {
		t.Fatalf("materialize device key: %v", err)
	}
	dir := filepath.Join(home, ".claude", "skillctl")
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	// Registered AFTER t.TempDir's cleanup → runs BEFORE it, so RemoveAll works.
	t.Cleanup(func() { _ = os.Chmod(dir, 0o700) })
}

// gateEntrypointFor mirrors the main.go dispatch for the two gate verbs (see
// main.go: case "verify-hook" → runVerifyHook, case "enforce" → runEnforce).
func gateEntrypointFor(t *testing.T, sub string) func(io.Reader, io.Writer, io.Writer) int {
	t.Helper()
	switch sub {
	case "verify-hook":
		return runVerifyHook
	case "enforce":
		return runEnforce
	}
	t.Fatalf("generated gate command wires a subcommand main.go does not dispatch: %q", sub)
	return nil
}

const gateSkillEvent = `{"tool_name":"Skill","tool_input":{"skill":"some-plugin:thing"},"session_id":"s"}`

// The headline E2E: the artifact of `pin generate --require-local-audit`, run
// against an unwritable audit path, refuses the allow (fail-closed, exit 26 in
// the deny message) instead of silently passing.
func TestPinGenerate_RequireLocalAudit_ArtifactFailsClosed(t *testing.T) {
	b := generatePinSettings(t, "--require-local-audit")
	cmd := preToolUseCommandFromJSON(t, b)
	if want := "/usr/local/bin/skillctl enforce"; cmd != want {
		t.Fatalf("gate command must wire the flag's only consumer: want %q, got %q", want, cmd)
	}
	if !pin.RequireLocalAuditFromBytes(b) {
		t.Fatal("generated settings must carry the enterprise-gated R-8.2 flag")
	}
	wireManagedSeamsFromBytes(t, b)
	brokenAuditHome(t)

	fields := strings.Fields(cmd)
	gate := gateEntrypointFor(t, fields[len(fields)-1])
	var out, errb bytes.Buffer
	code := gate(strings.NewReader(gateSkillEvent), &out, &errb)
	if code != exitHookBlock {
		t.Fatalf("un-recordable allow under require_local_audit must fail closed (exit %d), got %d\nstdout=%s\nstderr=%s",
			exitHookBlock, code, out.String(), errb.String())
	}
	se := errb.String()
	if !strings.Contains(se, "exit 26") || !strings.Contains(se, "require_local_audit") {
		t.Errorf("deny must carry the local_audit_unavailable escalation (exit 26):\n%s", se)
	}
}

// Counter-case: without the flag the generated artifact keeps the verify-hook
// verb and the SAME broken audit path stays a silent allow (fire-and-forget,
// SPEC-0255): no exit 26 anywhere.
func TestPinGenerate_Default_ArtifactStaysFireAndForget(t *testing.T) {
	b := generatePinSettings(t)
	cmd := preToolUseCommandFromJSON(t, b)
	if want := "/usr/local/bin/skillctl verify-hook"; cmd != want {
		t.Fatalf("default gate command must stay verify-hook: got %q", cmd)
	}
	if pin.RequireLocalAuditFromBytes(b) {
		t.Fatal("default settings must not carry the R-8.2 flag")
	}
	wireManagedSeamsFromBytes(t, b)
	brokenAuditHome(t)

	fields := strings.Fields(cmd)
	gate := gateEntrypointFor(t, fields[len(fields)-1])
	var out, errb bytes.Buffer
	code := gate(strings.NewReader(gateSkillEvent), &out, &errb)
	if code != exitOK {
		t.Fatalf("without the flag the allow must stand (exit %d), got %d\nstderr=%s", exitOK, code, errb.String())
	}
	if s := errb.String(); strings.Contains(s, "exit 26") || strings.Contains(s, "local_audit_unavailable") {
		t.Errorf("no R-8.2 escalation may appear without the flag:\n%s", s)
	}
}
